#!/usr/bin/env bash

declare version
version="$(git describe --tags)"

docker build -t "kristofferahl/es-curator-index-pruner:${version:?}" .
docker tag "kristofferahl/es-curator-index-pruner:${version:?}" kristofferahl/es-curator-index-pruner:latest
