#!/usr/bin/env bash

export ES_HOST
export ES_PORT
export ES_USERNAME
export ES_PASSWORD
export ES_USE_SSL
export ES_SSL_NO_VALIDATE
export INDEX_OLDER_THAN_DAYS
export INDEX_PREFIX

ES_HOST=''
ES_PORT=9200
ES_USERNAME='kibana'
ES_PASSWORD='kibana'
ES_USE_SSL=False
ES_SSL_NO_VALIDATE=True
INDEX_OLDER_THAN_DAYS=''
INDEX_PREFIX=''

declare name="${1:?'A name must be given (used for .env files)'}"
declare dotenv_file="./.env.${name:?}"
if [[ -f ${dotenv_file:?} ]]; then
  echo "Sourcing ${dotenv_file:?} file"
  # shellcheck source=/dev/null
  source "${dotenv_file:?}"
else
  echo "No .env file found! (${dotenv_file:?})"
  exit 1
fi

docker run --rm \
  -e ES_HOST="${ES_HOST:?}" \
  -e ES_PORT=${ES_PORT:?} \
  -e ES_USERNAME="${ES_USERNAME:?}" \
  -e ES_PASSWORD="${ES_PASSWORD:?}" \
  -e ES_USE_SSL=${ES_USE_SSL:?} \
  -e ES_SSL_NO_VALIDATE=${ES_SSL_NO_VALIDATE:?} \
  -e INDEX_OLDER_THAN_DAYS="${INDEX_OLDER_THAN_DAYS}" \
  -e INDEX_PREFIX="${INDEX_PREFIX}" \
kristofferahl/es-curator-index-pruner:latest
